# Configuration JSP
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Logs d�taill�s pour LDAP
logging.level.org.springframework.web=DEBUG
# Logs d�taill�s pour LDAP et s�curit�
logging.level.org.springframework.security.ldap=TRACE
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.ldap=DEBUG
logging.level.com.example.spring_ad_auth.config=DEBUG
logging.level.org.springframework.security.ad=DEBUG



spring.datasource.url = jdbc:h2:mem:testdb
spring.h2.console.enabled = true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.path = /h2-console

# Configuration Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Chemin o� les fichiers seront stock�s sur le serveur (Cr�ez ce dossier � la racine du projet)
upload.path=./uploads/


spring.ai.ollama.base-url=http://localhost:11434
# Assurez-vous que le nom ici est EXACTEMENT le m�me que dans 'ollama list'
spring.ai.ollama.chat.options.model=phi3:mini
# Augmentez le timeout (Phi-3 peut mettre du temps � charger la premi�re fois)
spring.ai.ollama.chat.options.temperature=0.5

server.tomcat.connection-timeout=60000




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=youssefibourk322@gmail.com
spring.mail.password=uvwd nojw dnvw kgmm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


ad.domain=test.local
ad.url=ldap://192.168.56.100:389
ad.rootDn=DC=test,DC=local
# Indique au driver LDAP d'ignorer les liens vers d'autres serveurs/partitions
spring.ldap.template.ignore-partial-result-exception=true

# Force JNDI � ignorer les r�f�rences au niveau de l'environnement
spring.ldap.base-environment.java.naming.referral=ignore


# Le login AD de la personne qui installe le logiciel
app.security.initial-admin=admin_iso


# Configuration de recherche LDAP/AD
spring.ldap.urls=ldap://192.168.56.100:389
spring.ldap.base=DC=test,DC=local
# Compte de service pour la recherche
spring.ldap.username=admin_iso@test.local
spring.ldap.password=P@ssword123


# Change 'update' par 'create-drop' pour une seule ex�cution
spring.jpa.hibernate.ddl-auto=create-drop