# Configuration JSP
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Logs détaillés pour LDAP
logging.level.org.springframework.web=DEBUG
# Logs détaillés pour LDAP et sécurité
logging.level.org.springframework.security.ldap=TRACE
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.ldap=DEBUG
logging.level.com.example.spring_ad_auth.config=DEBUG

spring.datasource.url = jdbc:h2:mem:testdb
spring.h2.console.enabled = true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.path = /h2-console

# Configuration Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Chemin où les fichiers seront stockés sur le serveur (Créez ce dossier à la racine du projet)
upload.path=./uploads/