server.servlet.register-default-servlet=true

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security.ldap=TRACE
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.ldap=DEBUG
logging.level.com.example.spring_ad_auth.config=DEBUG
logging.level.org.springframework.security.ad=DEBUG



spring.datasource.url = jdbc:h2:mem:testdb
spring.h2.console.enabled = true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.path = /h2-console

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

upload.path=./uploads/


spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=phi3:mini
spring.ai.ollama.chat.options.temperature=0.5

server.tomcat.connection-timeout=60000




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=youssefibourk322@gmail.com
spring.mail.password=uvwd nojw dnvw kgmm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


ad.domain=test.local
ad.url=ldap://192.168.56.100:389
ad.rootDn=DC=test,DC=local
spring.ldap.template.ignore-partial-result-exception=true

spring.ldap.base-environment.java.naming.referral=ignore


app.security.initial-admin=admin_iso


spring.ldap.urls=ldap://192.168.56.100:389
spring.ldap.base=DC=test,DC=local
spring.ldap.username=admin_iso@test.local
spring.ldap.password=P@ssword123


spring.jpa.hibernate.ddl-auto=create-drop

app.excel.dda-path=D:/Downoalds/spring-ad-auth/spring-ad-auth/app-data/DDA.xlsx
app.excel.risk-path=D:/Downoalds/spring-ad-auth/spring-ad-auth/app-data/risques_final.xlsx
app.excel.assets-path=D:/Downoalds/spring-ad-auth/spring-ad-auth/app-data/Inventaire_Actifs.xlsx
app.excel.journal-path=D:/Downoalds/spring-ad-auth/spring-ad-auth/app-data/Journal_Amelioration.xlsx